### ISSUE TITLE
Add STATIC_NONE static type for use with Optional<T>

### ISSUE THREAD

**Issue by leighmcculloch** [stellar/rs-stellar-contract-env#105]
Add `STATIC_NONE` static type for use with `Option<T>`.

The static type needs extending to include a `STATIC_NONE` value.

The value will be used by the `Option<T>` when a type can be stored as a type or a STATIC_NONE.

Related discussion: https://discord.com/channels/897514728459468821/982314893237714967

**Comment by graydon** [comment]
You're sure you prefer this over a union-with-VOID? I only ask because .. opinions vary in languages like eg. Javascript whether it is useful rather than confusing to have multiple kinds of "missing value" sentinel (null vs. undefined).

**Comment by leighmcculloch** [comment]
I was under the impression someone preferred OPTION_NONE, but if Vec is fine 🎉

**Comment by graydon** [comment]
I prefer having a value in guest-space to union-with rather than using an empty vec -- a vec default allocates 256 elements, where each element is an `EnvVal` holding an `(scval,weak)` pair so 16 bytes, meaning an "empty" vec costs 4kb (this is possibly an argument for doing a small-vec optimization in the future).

I'm just not sure whether `NONE` is importantly-different from `VOID`.

**Comment by leighmcculloch** [comment]
@graydon If @jayz22 adds #196 does that address your concern, or you'd still prefer the use of a static value for Option? If you'd prefer the use of a static Option, are you okay with NONE?

**Comment by leighmcculloch** [comment]
Closing because https://github.com/stellar/stellar-xdr-next/pull/11#issuecomment-1183573511.
